= {lab_name}

The `lab_name` var, known as an asciidoc attribute, above was set in `./content/antora.yml` and can be used to set the lab_name or title of your content.
You are both free to change its value and if you prefer to use a different var name, you can change the value of `lab_name`, for example to `title` in `./content/antora.yml` and then reference it in your content as `\{title}`.

== Variables

Other vars can also be set there, such as `ssh_user` and `ssh_password`, and referenced inline in the lab content by using the `\{foo}` syntax.

This is another var, or asciidoc attribute, from `./content/antora.yml` {my_var}

{rhdh_url}

{console_url}

{gitlab_url}

your user_id is: {user}

your user_number is: {usernum}

your namespaces are: 
 * link:{console_url}/topology/ns/{namespace}[{namespace}]
 * link:{console_url}/topology/ns/{namespace}-preprod[{namespace}-preprod]
 * link:{console_url}/topology/ns/{namespace}-prod[{namespace}-prod]

By the end of this workshop, you’ll know the basics of Red Hat Developer Hub, Backstage Software Templates, and the architecture of the example app. 
