= {lab_name}

Welcome, {user}!

In order to follow along with this workshop adaptation of link:https://developers.redhat.com/e-books/developer-portals[Developer Portals: Prepare to Perform with the Red Hat Developer Hub], you will need to create three namespaces in the link:{console_url}[openshift web console]:

1. First, open the link:{console_url}[openshift web console] in a new browser window.
2. Select the *rhsso* login option.
3. Enter your username (`{user}`) and password when prompted.
4. Click on `create a Project` to create a new project namespace in OpenShift.
5. Enter your first project name (`{namespace}`)
6. Click on the project dropdown and select the *Create Project* button to create a second project named `{namespace}-preprod`
7. Repeat the previous step to create a third project named `{namespace}-prod` 

After creating the three namespaces, you should be ready to proceed.

By the end of this workshop, you’ll know the basics of Red Hat Developer Hub, the Software Catalog, Backstage Software Templates, and have an understanding of how templates can be used to reign in project complexity.
