= {lab_name}

The `lab_name` var, known as an asciidoc attribute, above was set in `./content/antora.yml` and can be used to set the lab_name or title of your content.
You are both free to change its value and if you prefer to use a different var name, you can change the value of `lab_name`, for example to `title` in `./content/antora.yml` and then reference it in your content as `\{title}`.

== Variables

Other vars can also be set there, such as `ssh_user` and `ssh_password`, and referenced inline in the lab content by using the `\{foo}` syntax.

This is another var, or asciidoc attribute, from `./content/antora.yml` {my_var}

{devspaces_url}

{rhdh_url}

{gitlab_url}

your user_id is: {user}

= About the preview edition

This fragment invites you into our thinking as we write a developer’s guide to developer portals. In the first chapter, you’ll learn what an internal developer portal is and the problems addressed by this category of software. To practically apply those ideas, you’ll examine Red Hat Developer Hub (RHDH), built around the open source Backstage core to implement an enterprise distribution of a platform for creating developer portals.

Subsequent chapters present some of the tools found in an RHDH instance and their representation in the RHDH user interface, then show you how to work with those tools to build an application. By the end of this preview, you’ll know the basics of Backstage Software Templates and the architecture of the example app. 

We hope this advance screening will leave you informed about why IDPs are having a moment and intrigued enough to read the complete first edition when it is available. We’ll do our best to deliver insights about developer portals in modern development in terms of Backstage and RHDH, which together represent the pioneering implementation of developer portal concepts.
